version: '3.8'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4174:4173" # Map port 3000 on the host to port 4173 inside the container
    environment:
      NODE_ENV: production
    # restart: always
